import { CreateProductDto } from '@resources/product/dto/create-product.dto';

export const DUMMY_PRODUCTS: CreateProductDto[] = [
  {
    id: 1,
    name: 'Laptop Gamer RTX 4060',
    stock: 5,
    price: 956000,
    category: 'Laptops',
    sales: 20,
  },
  {
    id: 2,
    name: 'Monitor UltraWide 34”',
    stock: 8,
    price: 259000,
    category: 'Monitors',
    sales: 10,
  },
  {
    id: 2,
    name: 'Monitor UltraWide 19”',
    stock: 18,
    price: 150000,
    category: 'Monitors',
    sales: 6,
  },
  {
    id: 3,
    name: 'Teclado Mecánico RGB',
    stock: 20,
    price: 35990,
    category: 'Keyboards',
    sales: 9,
  },
  {
    id: 4,
    name: 'Mouse Inalámbrico Logitech',
    stock: 15,
    price: 12990,
    category: 'Mice',
    sales: 19,
  },
  {
    id: 5,
    name: 'Silla Ergonómica Gamer',
    stock: 7,
    price: 57990,
    category: 'Chairs',
    sales: 30,
  },
  {
    id: 6,
    name: 'Disco Duro Externo 2TB',
    stock: 12,
    price: 34990,
    category: 'Storage',
    sales: 49,
  },
  {
    id: 7,
    name: 'Tarjeta Gráfica RTX 4070',
    stock: 3,
    price: 890000,
    category: 'Graphics Cards',
    sales: 4,
  },
  {
    id: 8,
    name: 'Procesador Intel i9 13th Gen',
    stock: 6,
    price: 549000,
    category: 'Processors',
    sales: 7,
  },
  {
    id: 9,
    name: 'Auriculares Inalámbricos Sony',
    stock: 10,
    price: 19900,
    category: 'Headphones',
    sales: 0,
  },
  {
    id: 10,
    name: 'Camara Web 4K',
    stock: 9,
    price: 14990,
    category: 'Webcams',
    sales: 100,
  },
];
